### PR TITLE
Dump the game's dialogue

### PR DESCRIPTION
**Pull request by Sanqui**
I also removed some cruft.  You'll need to use latest rgbds now.

### CODE REVIEW

**Comment by kemenaran** [comment]
That look awesome, thanks for the work!

I'm currently traveling, and won't be able to merge this before one week or two – but I just had a quick look through it, and it looks great.

**Comment by Sanqui** [comment]
Thanks!  There's certainly no hurry.  I might be doing more text-related stuff or I might drop it entirely for a few months, with me you never know.

**Comment by kemenaran** [comment]
I took some time to have a look today, and it looks great. Nice to get the dialogs dumped, and the build process improved with rgbds overlays.

**Comment by kemenaran** [comment]
Merged. Thanks for the PR!

By the way, I'm still struggling with producing valid (uncommented) disassembly for the remaining banks. For now I'm working on [upgrading pret's pokemon disassembling tools](https://github.com/kemenaran/pokemon-reverse-engineering-tools/tree/improve-gb-disasm?files=1) to produce a valid (and symbols-aware) disassembly. It kind of works, but the base code of the disassembler is such an untested mess I wonder if I should start from scratch. If you have any hints or tools, I'm definitely looking for alternatives.

**Pull request merged**
