### PR TITLE
Fix building and all errors causing mismatches with the rom

### PR DESCRIPTION
**Pull request by Drenn1**
As the title says, I've gone and fixed up this disassembly so that

A) It compiles
B) It produces an exact copy of the original rom

I've also added a check to the makefile to confirm, every build, that the ROM is an exact copy of the original. I hope cygwin has the md5sum command by default? Anyway, this will immediately warn you if you make a mistake which causes a deviation from the rom.

By the way, I just know that you used [this opcode map](http://imrannazar.com/Gameboy-Z80-Opcode-Map). It's missing opcode $f2. I found that out the hard way! In addition, you misunderstood opcode $e2, which is similar to $f2. You had it compiling as `ld a,($FF0C)`, but it really should have been `ld a,($FF00+C)`, where "C" is the C register!

Another cause of deviations from the rom was the "halt" opcode. rgbds tries to be helpful by inserting a "nop" opcode after every "halt" opcode, in order to circumvent a bug on the original gameboy, but there's no guarantee that games will do that... particularly when you've disassembled data as code. It might be worth re-running Z80Dis.c to regenerate the files in src/disassembled-banks - as it stands, I doubt they will compile correctly.

Aside from those issues, there were a few mistakes from what I assume was manual reorganization in bank1.asm. Those kinds of mistakes are easy enough to make, but now you'll be warned about them. :)

### CODE REVIEW

**Comment by kemenaran** [comment]
I tested this, and indeed it compiles an executable ROM.

👍

**Comment by mojobojo** [comment]
Sorry about the late merge. I will try to pay attention to this git more now that it has some activity.

**Comment by Drenn1** [comment]
You should be able to turn on email notifications for new pull requests and that sort of thing.

**Comment by mojobojo** [comment]
I turned on notifications, thanks. On a side note I made a slight change to the makefile because mingw would error out in making DumpBanks and the chmod.

**Pull request merged**
